### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by thymaro** [zph/joplin-plugin-auto-tags#1]
Hi, I downloaded this plugin from the repository and added some octothorpe words to a note. Then I was looking for a way to make the magic of this plugin happen. I couldn't find out, whether it was automatic when switching to another note, whether there was an interface button somewhere or if I could find a clue in some context menu.

How do I rev up the gears on this?

Also, there's no link to this page in the joplin plugins list and the link to your other plugin is wrong, unfortunately. I'm gonna go and fix that, actually. This is github, afterall.

**Comment by thymaro** [comment]
Ok, I can't commit PRs to the joplin master branch, because most of the content is auto-generated. I guess you'd need to edit some of the links in your plugin code, then.

**Comment by g33k247** [comment]
Does not work. No respones.

**Comment by zph** [comment]
I folks. I've stopped using joplin and am not maintaining these plugins.

Please fork the repository and update it if you're interested to maintain it.
